name: CDK Build and Test

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CDK_DISABLE_CLI_TELEMETRY: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2

      - uses: astral-sh/setup-uv@v7

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Run Make
        run: make
